services:
  - type: web
    name: dreamlitai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: PORT
        value: 5000
    healthCheckPath: /health
